version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: .
          pip-dependency-file: requirements.txt
      - run:
          name: Run pytest
          command: pytest -q --maxfail=1 --disable-warnings

workflows:
  run-tests:
    jobs:
      - test
