version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12-browsers
    environment:
      FLASK_APP: simpler_server
      FLASK_ENV: testing
      TEST_BASE_URL: http://127.0.0.1:5000
    steps:
      - checkout

      - run:
          name: Show runtime versions
          command: |
            python --version
            pip --version
            google-chrome --version || true
            chromedriver --version || true

      - python/install-packages:
          pkg-manager: pip
          app-dir: .
          pip-dependency-file: requirements.txt

      - run:
          name: Start Flask (background) + wait until it's up
          command: |
            python -m flask --app "$FLASK_APP" run --port 5000 > flask.log 2>&1 &
            echo $! > flask.pid

            for i in $(seq 1 60); do
              curl -sSf "$TEST_BASE_URL/" >/dev/null 2>&1 && echo "Flask is up" && break
              sleep 1
            done
            head -n 40 flask.log || true

      - run:
          name: Run pytest
          command: pytest -q --maxfail=1 --disable-warnings

      - run:
          name: Show Flask logs on failure
          when: on_fail
          command: |
            echo "==== flask.log ===="
            cat flask.log || true

      - run:
          name: Stop Flask
          command: |
            if [ -f flask.pid ]; then kill -INT "$(cat flask.pid)" || true; fi

workflows:
  run-tests:
    jobs:
      - test
workflows:
  run-tests:
    jobs:
      - test
