version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12-browsers
    environment:
      FLASK_APP: simpler_server.py
      FLASK_ENV: testing
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: .
          pip-dependency-file: requirements.txt
      - run:
          name: Start Flask
          command: |
            python -m flask --app simpler_server run --port 5000 > flask.log 2>&1 &
            sleep 5
      - run:
          name: Run pytest
          command: pytest -q --maxfail=1 --disable-warnings
      - run:
          name: Show Flask logs if tests fail
          when: on_fail
          command: cat flask.log || true

workflows:
  run-tests:
    jobs:
      - test
